# Generated by Django 4.0.3 on 2023-01-24 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_rename_assigned_technician_appointment_technician_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='canceled',
            new_name='cancelled',
        ),
    ]
