# Generated by Django 4.0.3 on 2023-01-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_remove_appointment_time_alter_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='start',
        ),
    ]
